[versions]
compileSdk = "35"
minSdk = "25"
targetSdk = "35"
buildToolsVersion = "35.0.0"


org-jetbrains-kotlin-android = "2.2.0"
coreKtx = "1.16.0"
activityKtx = "1.10.1"
fragmentKtx = "1.8.8"
appcompat = "1.7.1"
appcompatV7 = "28.0.0"
material = "1.12.0"
constraintlayout = "2.2.1"
lifecycle = "2.9.1"
recyclerview = "1.4.0"
koinAndroidExt = "3.0.2"
koin = "4.1.0"

lifecycle-extensions="2.2.0"
lifecycleViewmodel = "2.8.3"
lifecycleLivedata = "2.8.3"

workRuntime="2.10.2"
workRuntimeKtx="2.10.2"

navigation = "2.9.1"
unpeopleLivedata= "4.4.1-beta1"
multidex = "2.0.1"
preferenceKtx= "1.2.1"
startupruntime= "1.2.0"

androidGradlePlugin = "8.11.0"

xxPermissions="18.5"
androidTools = "31.11.0"
unspecified = "1.1.0"

androidComposeUi= "1.8.3"
refresh-layout = "2.1.1"

retrofit = "3.0.0"
converter_gson = "3.0.0"
adapter_rxjava3 = "3.0.0"
converter_scalars = "3.0.0"
converter-simplexml = "3.0.0"
jsoup="1.21.1"

rxjava = "3.1.11"
rxAndroid = "3.0.2"
rxLifecycle = "2.2.2"

okhttp3 = "5.1.0"
okio = "3.15.0"
logging_interceptor = "5.1.0"

glide ="4.16.0"
glideCompiler = "4.16.0"

gosn="2.13.1"


roomRuntime="2.7.2"
roomCompiler="2.7.2"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat"}
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }

appcompatV7 = { module = "com.android.support:appcompat-v7", version.ref = "appcompatV7"}


#viewModel ,#lifecycle
lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle"}
lifecycleLivedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle"}
koinAndroidExt = { module = "io.insert-koin:koin-android-ext", version.ref = "koinAndroidExt" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle"}
lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle"}
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions"}
workRuntime = { module = "androidx.work:work-runtime", version.ref = "workRuntime"}
workRuntimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx"}

# unpeopleLivedata
unpeopleLivedata = { module = "com.kunminx.archi:unpeople-livedata", version.ref = "unpeopleLivedata"}



#navigation
navigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation"}
navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation"}

preferenceKtx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx"}
supportMultidex = { module = "androidx.multidex:multidex", version.ref = "multidex"}
startupruntime = { module = "androidx.startup:startup-runtime", version.ref = "startupruntime"}


xxPermissions= { module = "com.github.getActivity:XXPermissions", version.ref = "xxPermissions" }
androidComposeUi = { module = "androidx.compose.ui:ui-android", version.ref = "androidComposeUi"}


lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "androidTools" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "androidTools" }

refresh-layout = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "refresh-layout" }
refresh-header = { module = "io.github.scwang90:refresh-header-classics", version.ref = "refresh-layout" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter_gson" }
adapter_rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "adapter_rxjava3" }
converter_scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converter_scalars" }
converter-simplexml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "converter-simplexml" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }


#Rxjava3
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxAndroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxAndroid" }
rxLifecycle = { module = "com.trello.rxlifecycle2:rxlifecycle-components", version.ref = "rxLifecycle" }

#gson
gson = { module = "com.google.code.gson:gson", version.ref = "gosn" }

#OkHttp
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
logging_interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging_interceptor" }

#glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }

#room
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android"}
