plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize' // 使用新的插件
}

android {
    namespace 'com.jetpack.mvvm'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.jetpack.mvvm"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        multiDexEnabled = true
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    buildFeatures {
        dataBinding = true  //数据绑定
        viewBinding = true  //view绑定
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation (libs.supportMultidex)
    implementation (libs.coreKtx)
    implementation (libs.appcompat)
    implementation (libs.recyclerview)
    implementation (libs.material)
    implementation (libs.constraintlayout)
    //lifecycle
    implementation (libs.lifecycleRuntimeKtx)
    implementation (libs.lifecycleCommonJava8)
    implementation (libs.lifecycleExtensions)
    implementation (libs.workRuntime)
    implementation (libs.workRuntimeKtx)
    // viewModel
    implementation (libs.lifecycleViewmodelKtx)
    // liveData
    implementation (libs.lifecycleLivedata)

    implementation (libs.activityKtx)

    //fragment
    implementation (libs.fragmentKtx)

    //navigation
    implementation (libs.navigationFragment)
    implementation (libs.navigationUi)


    implementation (libs.preferenceKtx)
    implementation (libs.supportMultidex)

    implementation(libs.refresh.layout)    // 核心必须依赖
    implementation(libs.refresh.header)    // 经典刷新头

    //圖片加載
    implementation(libs.glide)
    kapt(libs.glideCompiler)

    //kotlin
    implementation (libs.okio)
    implementation(libs.koinAndroidExt)
    implementation(libs.koinAndroid)

    //图片选择的框架
    implementation 'io.github.lucksiege:pictureselector:v2.7.3-rc10'
    implementation "com.robinhood.ticker:ticker:2.0.2"
    implementation "javax.inject:javax.inject:1"
    implementation "javax.annotation:javax.annotation-api:1.3.2"

    implementation "com.jakewharton.timber:timber:5.0.1"
    implementation "com.github.PhilJay:MPAndroidChart:v3.0.3"

    implementation "com.google.dagger:hilt-android:2.56"
    kapt "com.google.dagger:hilt-compiler:2.56"


    implementation "com.jakewharton.threetenabp:threetenabp:1.4.6"

    implementation "io.coil-kt:coil:2.7.0"

    implementation (libs.retrofit)
    implementation (libs.converterGson)
    implementation (libs.adapter.rxjava3)
    implementation (libs.converter.scalars)
    implementation (libs.converter.simplexml)
    implementation (libs.jsoup)

    //room
    implementation(libs.roomRuntime)
    kapt(libs.roomCompiler)

    //项目核心框架
    implementation project(':framework_mvvm')
    implementation project(':framework_http')//http框架
    implementation(project(":autosize"))

}